import React from 'react';
import { Menu } from 'lucide-react';
import Home from '../src/pages/Home';
import About from '../src/pages/About';
import Projects from '../src/pages/Projects';
import Certifications from '../src/pages/Certifications';
import Contact from '../src/pages/Contact';

function App() {
  const [isMenuOpen, setIsMenuOpen] = React.useState(false);
  const [, setActiveSection] = React.useState('home');

  const scrollToSection = (sectionId: string) => {
    const element = document.getElementById(sectionId);
    if (element) {
      element.scrollIntoView({ behavior: 'smooth' });
      setActiveSection(sectionId);
      setIsMenuOpen(false);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-b from-[#0d1117] via-[#161b22] to-[#1f2937]"> {/* background generated by AI*/}
      {/* Navigation */}
      <nav className="fixed top-0 left-0 right-0  backdrop-blur-sm z-50 border-b bg-gradient-to-b from-[#0d1117] via-[#161b22] to-[#1f2937]">
        <div className="max-w-7xl mx-auto px-4 sm:px-6">
          <div className="flex justify-between h-16 items-center">
            <button 
              onClick={() => scrollToSection('home')} 
              className="text-xl font-medium text-slate-200 font-mono"
            >
              Harsha Vardhan
            </button>

            {/* Desktop Navigation */}
            <div className="hidden md:flex space-x-6">
              <button onClick={() => scrollToSection('home')} className="px-2 py-1 bg-blue-600 text-white rounded-lg transition-all duration-300 ease-in-out
               hover:shadow-[0_0_15px_4px_rgba(59,130,246,0.6)] hover:ring hover:ring-blue-400/50 ">Home</button>
              <button onClick={() => scrollToSection('about')} className="px-2 py-1 bg-blue-600 text-white rounded-lg transition-all duration-300 ease-in-out
               hover:shadow-[0_0_15px_4px_rgba(59,130,246,0.6)] hover:ring hover:ring-blue-400/50">About</button>
              <button onClick={() => scrollToSection('projects')} className="px-2 py-1 bg-blue-600 text-white rounded-lg transition-all duration-300 ease-in-out
               hover:shadow-[0_0_15px_4px_rgba(59,130,246,0.6)] hover:ring hover:ring-blue-400/50">Projects</button>
              <button onClick={() => scrollToSection('certifications')} className="px-2 py-1 bg-blue-600 text-white rounded-lg transition-all duration-300 ease-in-out
               hover:shadow-[0_0_15px_4px_rgba(59,130,246,0.6)] hover:ring hover:ring-blue-400/50">Certifications</button>
              <button onClick={() => scrollToSection('contact')} className="px-2 py-1 bg-blue-600 text-white rounded-lg transition-all duration-300 ease-in-out
               hover:shadow-[0_0_15px_4px_rgba(59,130,246,0.6)] hover:ring hover:ring-blue-400/50">Contact</button>
            </div>

            {/* Mobile menu button */}
            <div className="md:hidden">
              <button
                onClick={() => setIsMenuOpen(!isMenuOpen)}
                className="text-slate-400 hover:text-slate-200"
              >
                <Menu size={24} />
              </button>
            </div>
          </div>
        </div>

        {/* Mobile Navigation */}
        {isMenuOpen && (
          <div className="md:hidden">
            <div className="px-2 pt-2 pb-3 space-y-1 sm:px-3 bg-slate-800 border-t border-slate-700">
              <button onClick={() => scrollToSection('home')} className="block w-full text-left px-3 py-2 text-slate-400 hover:text-slate-200">Home</button>
              <button onClick={() => scrollToSection('about')} className="block w-full text-left px-3 py-2 text-slate-400 hover:text-slate-200">About</button>
              <button onClick={() => scrollToSection('projects')} className="block w-full text-left px-3 py-2 text-slate-400 hover:text-slate-200">Projects</button>
              <button onClick={() => scrollToSection('certifications')} className="block w-full text-left px-3 py-2 text-slate-400 hover:text-slate-200">Certifications</button>
              <button onClick={() => scrollToSection('contact')} className="block w-full text-left px-3 py-2 text-slate-400 hover:text-slate-200">Contact</button>
            </div>
          </div>
        )}
      </nav>

      {/* Main Content */}
      <main className="pt-20 ">
        <section id="home" className="scroll-mt-16">
          <Home />
        </section>
        <section id="about" className="">
          <About />
        </section>
        <section id="projects" className="">
          <Projects />
        </section>
        <section id="certifications" className="">
          <Certifications />
        </section>
        <section id="contact" className="scroll-mt-12">
          <Contact />
        </section>
    </main>

    </div>
  );
}

export default App;
